//THIS CODE WAS CREATED BY A TOOL, REGENERATE IT USING "npm run data"
export default [
  /Alberta/iu,
  /AB/iu,
  [/British/iu, /Columbia/iu],
  /BC/iu,
  /Manitoba/iu,
  /MB/iu,
  [/New/iu, /Brunswick/iu],
  /NB/iu,
  [/Newfoundland/iu, /and/iu, /Labrador/iu],
  /NL/iu,
  [/Northwest/iu, /Territories/iu],
  /NT/iu,
  [/Nova/iu, /Scotia/iu],
  /NS/iu,
  /Nunavut/iu,
  /NU/iu,
  /Ontario/iu,
  /ON/iu,
  [/Prince/iu, /Edward/iu, /Island/iu],
  /PE/iu,
  /Quebec/iu,
  /QC/iu,
  /Saskatchewan/iu,
  /SK/iu,
  /Yukon/iu,
  /YT/iu
];
