//THIS CODE WAS CREATED BY A TOOL, REGENERATE IT USING "npm run data"
export default [
  "Alberta",
  "AB",
  ["British", "Columbia"],
  "BC",
  "Manitoba",
  "MB",
  ["New", "Brunswick"],
  "NB",
  ["Newfoundland", "and", "Labrador"],
  "NL",
  ["Northwest", "Territories"],
  "NT",
  ["Nova", "Scotia"],
  "NS",
  "Nunavut",
  "NU",
  "Ontario",
  "ON",
  ["Prince", "Edward", "Island"],
  "PE",
  "Quebec",
  "QC",
  "Saskatchewan",
  "SK",
  "Yukon",
  "YT"
];
