//THIS CODE WAS CREATED BY A TOOL, REGENERATE IT USING "npm run data"
export default [
  /Alabama/iu,
  /AL/iu,
  /Alaska/iu,
  /AK/iu,
  /Arizona/iu,
  /AZ/iu,
  /Arkansas/iu,
  /AR/iu,
  /California/iu,
  /CA/iu,
  /Colorado/iu,
  /CO/iu,
  /Connecticut/iu,
  /CT/iu,
  /Delaware/iu,
  /DE/iu,
  /Florida/iu,
  /FL/iu,
  /Georgia/iu,
  /GA/iu,
  /Hawaii/iu,
  /HI/iu,
  /Idaho/iu,
  /ID/iu,
  /Illinois/iu,
  /IL/iu,
  /Indiana/iu,
  /IN/iu,
  /Iowa/iu,
  /IA/iu,
  /Kansas/iu,
  /KS/iu,
  /Kentucky/iu,
  /KY/iu,
  /Louisiana/iu,
  /LA/iu,
  /Maine/iu,
  /ME/iu,
  /Maryland/iu,
  /MD/iu,
  /Massachusetts/iu,
  /MA/iu,
  /Michigan/iu,
  /MI/iu,
  /Minnesota/iu,
  /MN/iu,
  /Mississippi/iu,
  /MS/iu,
  /Missouri/iu,
  /MO/iu,
  /Montana/iu,
  /MT/iu,
  /Nebraska/iu,
  /NE/iu,
  /Nevada/iu,
  /NV/iu,
  [/New/iu, /Hampshire/iu],
  /NH/iu,
  [/New/iu, /Jersey/iu],
  /NJ/iu,
  [/New/iu, /Mexico/iu],
  /NM/iu,
  [/New/iu, /York/iu],
  /NY/iu,
  [/North/iu, /Carolina/iu],
  /NC/iu,
  [/North/iu, /Dakota/iu],
  /ND/iu,
  /Ohio/iu,
  /OH/iu,
  /Oklahoma/iu,
  /OK/iu,
  /Oregon/iu,
  /OR/iu,
  /Pennsylvania/iu,
  /PA/iu,
  [/Rhode/iu, /Island/iu],
  /RI/iu,
  [/South/iu, /Carolina/iu],
  /SC/iu,
  [/South/iu, /Dakota/iu],
  /SD/iu,
  /Tennessee/iu,
  /TN/iu,
  /Texas/iu,
  /TX/iu,
  /Utah/iu,
  /UT/iu,
  /Vermont/iu,
  /VT/iu,
  /Virginia/iu,
  /VA/iu,
  /Washington/iu,
  /WA/iu,
  [/West/iu, /Virginia/iu],
  /WV/iu,
  /Wisconsin/iu,
  /WI/iu,
  /Wyoming/iu,
  /WY/iu,
  [/American/iu, /Samoa/iu],
  /AS/iu,
  [/District/iu, /of/iu, /Columbia/iu],
  /DC/iu,
  [/Federated/iu, /States/iu, /of/iu, /Micronesia/iu],
  /FM/iu,
  /Guam/iu,
  /GU/iu,
  [/Marshall/iu, /Islands/iu],
  /MH/iu,
  [/Northern/iu, /Mariana/iu, /Islands/iu],
  /MP/iu,
  /Palau/iu,
  /PW/iu,
  [/Puerto/iu, /Rico/iu],
  /PR/iu,
  [/Virgin/iu, /Islands/iu],
  /VI/iu,
  [/Armed/iu, /Forces/iu, /Africa/iu],
  /AE/iu,
  [/Armed/iu, /Forces/iu, /Americas/iu],
  /AA/iu,
  [/Armed/iu, /Forces/iu, /Canada/iu],
  /AE/iu,
  [/Armed/iu, /Forces/iu, /Europe/iu],
  /AE/iu,
  [/Armed/iu, /Forces/iu, /Middle/iu, /East/iu],
  /AE/iu,
  [/Armed/iu, /Forces/iu, /Pacific/iu],
  /AP/iu
];
